### ISSUE TITLE
DCSR Transposition Issue

### ISSUE THREAD

**Issue by jpr-snl** [sandialabs/LAPIS#74]
When trying to compile code that performs a simple transposition on a DCSR matrix, I get the following errors:
```
/home/jproose/projects/tensql/lapis_package/lapis_package_module.cpp: In function 'std::tuple<void*, long unsigned int, long unsigned int> lapis_main(void*)':
/home/jproose/projects/tensql/lapis_package/lapis_package_module.cpp:632:13: error: 'v52' was not declared in this scope; did you mean 'v42'?
  632 |       v48 = v52;
      |             ^~~
      |             v42
/home/jproose/projects/tensql/lapis_package/lapis_package_module.cpp:689:15: error: 'v52' was not declared in this scope; did you mean 'v59'?
  689 |         v71 = v52;
      |               ^~~
      |               v59
```

Here's the high level code I'm using.  The same code does not trigger the issue when using the LLVM backend.  
```
#sparse = #sparse_tensor.encoding<{ map = (d0, d1) -> (d0 : compressed, d1 : compressed) }>
module {
  func.func @main(%arg0: tensor<16x16xi64, #sparse>) -> (tensor<16x16xi64, #sparse>, index, index) attributes {llvm.emit_c_interface} {
    %0 = tensor.empty() : tensor<16x16xi64, #sparse>
    %transposed = linalg.transpose ins(%arg0 : tensor<16x16xi64, #sparse>) outs(%0 : tensor<16x16xi64, #sparse>) permutation = [1, 0]
    %rank = tensor.rank %transposed : tensor<16x16xi64, #sparse>
    %1 = sparse_tensor.number_of_entries %transposed : tensor<16x16xi64, #sparse>
    return %transposed, %rank, %1 : tensor<16x16xi64, #sparse>, index, index
  }
}
```

**Comment by jpr-snl** [comment]
Here's the generated C++ code:
[lapis_package_module.cpp.txt](https://github.com/user-attachments/files/20039489/lapis_package_module.cpp.txt)

**Comment by brian-kelley** [comment]
@jpr-snl After merging #93 (but possibly before this), I can lower/emit/compile this code without errors (for cuda or openmp backend).

**Comment by jpr-snl** [comment]
Yeah, I agree.  This one seems to be resolved in TenSQL.
